openapi: "3.1.0"
info:
  title: "multimodule01 API"
  description: "multimodule01 API"
  version: "1.0.0"
servers:
  - url: "https://multimodule01"
paths:
  /test:
    get:
      summary: "GET test"
      operationId: "test"
      responses:
        "200":
          description: "OK"
          content:
            'application/json':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/TestEntity"
components:
  schemas:
    TestEntity:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        data:
          type: "string"
      required:
        - "data"
